# Use Python base image
FROM python:3.11-slim

WORKDIR /usr/src/app

# Copy requirements and install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy simulation script
COPY lifeline_core.py .

# Run the simulation
CMD [ "python", "lifeline_core.py" ]
